services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - SELENIUM_TESTS=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports: 
      - "3001:3001"
      - "10678:10678"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - SELENIUM_TESTS=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "3000:3000"
  selenium-tests:
    build:
      context: ./selenium_tests
      dockerfile: ./Dockerfile
    command: pytest ./src/test_python_sample.py
    depends_on:
      - chrome
      - server
      - client
  selenium-tests-debug:
    build:
      context: ./selenium_tests
      dockerfile: ./Dockerfile
    command: python3 -m debugpy --listen 0.0.0.0:10679 --wait-for-client -m pytest ./src/test_python_sample.py
    ports: 
      - "10679:10679"
    depends_on:
      - chrome
      - server
      - client
  chrome:
    image: selenium/standalone-chrome-debug
    hostname: chrome
    ports:
      - "4444:4444"
      - "5900:5900"
