services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        BUILD_DEVELOPMENT: ${BUILD_DEVELOPMENT}
    environment:
      HOST_IP: "192.168.0.222"
    ports:
      - "3001:3001"
      - "10678:10678"
    volumes:
      - ./server:/server
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
