services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        BUILD_DEVELOPMENT: ${BUILD_DEVELOPMENT}
    command: bash -c "python -m debugpy --listen 0.0.0.0:10678 app.py"
    ports:
      - "3001:3001"
      - "10678:10678"
    volumes:
      - ./server:/server
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
