FROM selenium/standalone-chrome-debug

ENV PYTHONUNBUFFERED 1
USER root
RUN apt-get update && apt-get install -yq python3.8 python3-pip
RUN mkdir /server
ADD . /server/
WORKDIR /server
RUN ln -s /usr/bin/python3 /usr/local/bin/python
RUN pip3 install --upgrade pip
RUN pip3 install Flask selenium pytest