name: CI for Node.js React Sample App
on: [push]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - uses: actions/setup-python@v5
          with:
            python-version: 3.9

        - name: Install client
          run: yarn --cwd client install

        - name: Lint client source
          run: yarn --cwd client lint

        - name: Install server (Python) and lint
          run: |
            cd server
            python -m venv bb2_venv
            . ./bb2_venv/bin/activate
            pip install pipenv
            pip install cms-bluebutton-sdk
            pipenv lock
            pipenv install --system --deploy --ignore-pipfile
            flake8 --exclude bb2_venv --max-line-length 130
